name: Relese URL
on:
  workflow_call:
    secrets:
      RELEASE_MACHINE_TOKEN:
        required: true
    inputs:
      release_tag:
        required: true
        type: string
    outputs:
      upload_url:
        description: "URL to release"
        value: ${{ jobs.create_release.outputs.upload_url }}

jobs:
  create_release:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Copy Release Notes
        working-directory: ./.github
        run: |
          echo ${{ secrets.RELEASE_MACHINE_TOKEN }} | gh auth login --with-token
          gh api /repos/MeshInspector/MeshInspectorCode/releases/tags/${{inputs.release_tag}} | jq -r '. | .body' > input.txt
          python3 parse_notes.py
          CHANGELOG=$(cat output.txt)
          echo "CHANGELOG=${{CHANGELOG}}" >> $GITHUB_ENV
          echo "${{env.CHANGELOG}}"

      - name: Create Release
        if: ${{false}}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_MACHINE_TOKEN }}
          RELEASE_PATH: ../../releases/download/${{inputs.release_tag}}
        with:
          tag_name: ${{inputs.release_tag}}
          release_name: Release ${{inputs.release_tag}}
          draft: false
          prerelease: false
          body: |
            Autogenerated release
            
            Our macos package is not signed yet, so to install it, follow this simple steps:
            1. Install Homebrew, if it's not installed
               `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
            2. System Preferences -> Security & Privacy -> Genereal. Set "allow apps downloaded from" to "App Store and identified developers"
            3. Download the .pkg file, righ-click on it and select "Open With" -> Installer
            
            <table>
              <thead>
                <tr>
                  <th>OS</th>
                  <th>Release</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td align="center">Windows x64</td>
                  <td align="center">
                    <a href="${{env.RELEASE_PATH}}/MeshInspectorInstaller_${{inputs.release_tag}}.msi">msi</a>
                  </td>
                </tr>
                <tr>
                  <td align="center">Ubuntu 20 LTS x64</td>
                  <td align="center">
                    <a href="${{env.RELEASE_PATH}}/meshinspector_${{inputs.release_tag}}_ubuntu20.deb">deb</a>
                  </td>
                </tr>
                <tr>
                  <td align="center">Ubuntu 22 LTS x64</td>
                  <td align="center">
                    <a href="${{env.RELEASE_PATH}}/meshinspector_${{inputs.release_tag}}_ubuntu22.deb">deb</a>
                  </td>
                </tr>
                <tr>
                  <td align="center">Fedora 35 x64</td>
                  <td align="center">
                    <a href="${{env.RELEASE_PATH}}/meshinspector_${{inputs.release_tag}}.rpm">rpm</a>
                  </td>
                </tr>
                <tr>
                  <td align="center">MacOS x64</td>
                  <td align="center">
                    <a href="${{env.RELEASE_PATH}}/MeshInspector_${{inputs.release_tag}}_x64.pkg">x64 pkg</a>
                  </td>
                </tr>
                <tr>
                  <td align="center">MacOS arm</td>
                  <td align="center">
                    <a href="${{env.RELEASE_PATH}}/MeshInspector_${{inputs.release_tag}}_arm.pkg">arm pkg</a>
                  </td>
                </tr>
              </tbody>
            </table>