# This is a basic workflow to help you get started with Actions

name: Publish MeshInspector

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    timeout-minutes: 40
    # The type of runner that the job will run on
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.RELEASE_MACHINE_TOKEN }}
        
      - name: Find MeshInspector latest tag
        uses: rez0n/actions-github-release@main
        id: latest_tag
        with:
          repository: MeshRUs/MeshInspector
          type: nodraft
          token: ${{ secrets.RELEASE_MACHINE_TOKEN }}

      - name: Download release
        uses: robinraju/release-downloader@v1.3
        with:
          repository: MeshRUs/MeshInspector
          tag: ${{ steps.latest_tag.outputs.release }}
          fileName: "*"
          out-file-path: "downloads"
          token: ${{ secrets.RELEASE_MACHINE_TOKEN }}

      - name: Push empty commit
        run: |
          git commit --allow-empty -m "Empty release commit"
          git push
          git push origin ${{ steps.latest_tag.outputs.release }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_MACHINE_TOKEN }}
        with:
          owner: MeshRUs
          tag_name: ${{ steps.latest_tag.outputs.release }}
          release_name: Release ${{ steps.latest_tag.outputs.release }}
          body: Autogenerated release
          draft: false
          prerelease: false

      - name: Upload Windows Installer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_MACHINE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: downloads/MeshInspectorInstaller_${{ steps.latest_tag.outputs.release }}.msi
          asset_name: MeshInspectorInstaller_${{ steps.latest_tag.outputs.release }}.msi
          asset_content_type: application/x-msi

      - name: Upload Ubuntu Distribution
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_MACHINE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./downloads/meshinspector_${{ steps.latest_tag.outputs.release }}.deb
          asset_name: meshinspector_${{ steps.latest_tag.outputs.release }}.deb
          asset_content_type: application/vnd.debian.binary-package

      - name: Upload Fedora Distribution
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_MACHINE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./downloads/meshinspector_${{ steps.latest_tag.outputs.release }}.rpm
          asset_name: meshinspector_${{ steps.latest_tag.outputs.release }}.rpm
          asset_content_type: application/octet-streame