# This is a basic workflow to help you get started with Actions

name: Publish MeshInspector

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  find-private-release:
    timeout-minutes: 5
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      latest_tag: ${{ steps.latest_tag.outputs.tag}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MESHRUSBOT_TOKEN }}
        
      - name: Find MeshInspector latest tag
        uses: oprypin/find-latest-tag@v1
        id: latest_tag
        with:
          repository: MeshInspector/MeshInspectorCode
          releases-only: false
          token: ${{ secrets.RELEASE_MACHINE_TOKEN }}

      - name: Push empty commit
        if: ${{false}}
        run: |
          git config --global user.email "${{ secrets.MESHRUSBOT_EMAIL }}@gmail.com"
          git config --global user.name "MeshRusBot"
          git commit --allow-empty -m "Empty release commit"
          git tag ${{ steps.latest_tag.outputs.tag }}
          git push

      - name: Update Release Notes
        working-directory: .github
        env:
          RELEASE_PATH: ../../releases/download/${{inputs.release_tag}}
        run: |
          echo ${{ secrets.RELEASE_MACHINE_TOKEN }} | gh auth login --with-token
          gh api /repos/MeshInspector/MeshInspectorCode/releases/tags/${{steps.latest_tag.outputs.tag}} | jq -r '. | .body' > changelog.txt
          python3 update_release_body.py ${{env.RELEASE_PATH}} ${{steps.latest_tag.outputs.tag}}

      - name: Test
        working-directory: .github
        run: cat final_body.txt

      - name: Create Release
        if: ${{false}}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MESHRUSBOT_TOKEN }}
        with:
          tag_name: ${{steps.latest_tag.outputs.tag}}
          release_name: Release ${{inputs.release_tag}}
          draft: false
          prerelease: false
          body_path: .github/final_body.txt

      - name: Download private release
        if: ${{false}}
        uses: robinraju/release-downloader@v1.3
        with:
          repository: MeshInspector/MeshInspectorCode
          tag: ${{steps.latest_tag.outputs.tag}}
          fileName: "*"
          out-file-path: "downloads"
          token: ${{ secrets.RELEASE_MACHINE_TOKEN }}

      - name: Upload Installers
        if: ${{false}}
        working-directory: downloads
        run: |
            gh release upload \
                    --repository MeshInspector/MeshInspector \
                    --tag ${{steps.latest_tag.outputs.tag}} \
          MeshInspectorInstaller_${{steps.latest_tag.outputs.tag}}.msi \
                   meshinspector_${{steps.latest_tag.outputs.tag}}_ubuntu20.deb \
                   meshinspector_${{steps.latest_tag.outputs.tag}}_ubuntu22.deb \
                   meshinspector_${{steps.latest_tag.outputs.tag}}.rpm \
                   MeshInspector_${{steps.latest_tag.outputs.tag}}_x64.pkg \
                   MeshInspector_${{steps.latest_tag.outputs.tag}}_arm.pkg
